### ISSUE TITLE
I use Material UI react and get an error

### ISSUE THREAD

**Issue by jack2ky** [ansu5555/pdf-viewer-reactjs#11]
> ./node_modules/material-design-icons/iconfont/material-icons.css
> ModuleParseError: Module parse failed: Unexpected character '' (1:0)
> You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> (Source code omitted for this binary file)

I get the error when I load the page

```
import React, { useState } from 'react'
// import {Document, Page} from "react-pdf";
import PDFViewer from "pdf-viewer-reactjs"


export default function PDF() {
    return (
        <PDFViewer
            document="/doctor.pdf"
        />
    )
}
```

**Comment by ansu5555** [comment]
Let me check and I will update you on this

**Comment by JamieKieranMartin** [comment]
Having the same issue. @jack2ky are you using nextjs or no?

**Comment by ansu5555** [comment]
Tested with Material UI React example and its working as expected, hence closing the issue.

![image](https://user-images.githubusercontent.com/5373653/78145000-faf6bf00-744d-11ea-8358-08c73fd0159b.png)
