### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by josedager** [ansu5555/pdf-viewer-reactjs#13]
Im gettins this error,

`
./node_modules/pdfjs-dist/build/pdf.js
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted`

Can you help me to correct this issue?

**Comment by ansu5555** [comment]
This issue is due to mozilla/pdf.js. Please refer the below issue for details

[](https://github.com/mozilla/pdf.js/issues/10253)
