### ISSUE TITLE
Problem due to setState

### ISSUE THREAD

**Issue by SupreethBaliga** [ansu5555/pdf-viewer-reactjs#15]
I was using pdf-viewer-reactjs to load a pdf in my react app. When I'm not using setState in componentDidMount, the pdf viewer works fine. However, when I use the setState, it displays "Error loading pages." Basically, an error is caused when I re-render the page. Any idea how I can work around this problem?

**Comment by ansu5555** [comment]
Share your code or steps to reproduce.

**Comment by SupreethBaliga** [comment]
I found a workaround. I defined the PDF viewer as a pure component so that it does not update on setState.
