### ISSUE TITLE
encoded faild with cyrillic symbols 

### ISSUE THREAD

**Issue by YaroslavWeb** [ansu5555/pdf-viewer-reactjs#16]
[Screenshot with problem](http://prntscr.com/rhju9t)
On the left, the PDF is displayed in a new window of the electron, on the right, the PDF is inside the program.

Instead of symbols there are squares)

**Comment by ansu5555** [comment]
Could you please share me the pdf file ?

**Comment by YaroslavWeb** [comment]
[doc.pdf](https://github.com/ansu5555/pdf-viewer-reactjs/files/4343698/doc.pdf)

**Comment by NikitaRomanov1** [comment]
Hope you help, same problem

**Comment by ansu5555** [comment]
I tried with react in my machine and it worked... not sure whats the issue could you check once if the supported fonts are installed in your machine.

![image](https://user-images.githubusercontent.com/5373653/76881871-cd334700-689f-11ea-8747-52439a47b30f.png)

**Comment by YaroslavWeb** [comment]
I try open new window by this package https://www.npmjs.com/package/react-new-window 
In result I have squares in new window, but image loading is good

**Comment by ansu5555** [comment]
when opening pdf(searchable pdf documents) through **react-new-window** not only cyrillic symbols but other fonts are also not getting loaded. There is no error in the console though, its a issue with **react-new-window** and should be raised there.

Anyway there is a workaround if you print the pdf as image based pdf then it loads perfectly.
