### ISSUE TITLE
Is there a way to shrink the report 'frame'?

### ISSUE THREAD

**Issue by rchancey** [ansu5555/pdf-viewer-reactjs#17]
in all the examples the report is super wide and on a phone it is wider than the phone. Styling seems to have no effect on shrinking the viewer.. Is there a way to make the viewer fit the container?

**Comment by ansu5555** [comment]
you can pass your styling in **canvasCss** prop as a class

**Comment by rchancey** [comment]
Can you please paste an example? I tried a variety of things but anything I do messes up all the navigation. Can you show how to make the width like 500 rather than the default 1000? I am using this on a mobile so needs to be more narrow. I tried passing strings, a style as a string, tried a few things and no changes to the width and just messes up the panning :-(

**Comment by rchancey** [comment]
@ansu5555. the internal size is 1000px and fixed.. can you share an actual example of how to provide a custom size? When I tried it broke the navigation since when you pass in canvasCSS it will also send all the navigation over to the canvasCSS :-(
