### ISSUE TITLE
Is there a more responsive CSS for mobile? the nav buttons and width get all fouled

### ISSUE THREAD

**Issue by rchancey** [ansu5555/pdf-viewer-reactjs#18]
<img width="758" alt="Screen Shot 2020-03-27 at 12 37 23 PM" src="https://user-images.githubusercontent.com/29101431/77784063-e23e7180-7027-11ea-9594-4b2a8daf3577.png">

**Comment by ansu5555** [comment]
Fixed in latest release (2.0.3)

![image](https://user-images.githubusercontent.com/5373653/77884809-680a2900-7283-11ea-9d53-c1222209d63e.png)
