### ISSUE TITLE
Styles Override

### ISSUE THREAD

**Issue by richardtaylordawson** [ansu5555/pdf-viewer-reactjs#2]
When implementing this component it completely overrides the website styles with bootstrap. Was really hoping to use it :(

**Comment by ansu5555** [comment]
You can provide your own CSS classes, to override it's default style from bootstrap. Checkout the examples for details...

**Comment by gomitaana** [comment]
Any update ?
@richardtaylordawson you still using this repo?

**Comment by richardtaylordawson** [comment]
Sorry this issue can be closed, decided not to go with this repo
