### ISSUE TITLE
after importing PDFViewer project stop compiling.. 

### ISSUE THREAD

**Issue by sandeepdillerao** [ansu5555/pdf-viewer-reactjs#21]

**Comment by ansu5555** [comment]
Please provide error logs for further investigation

**Comment by vivek-gothi-openxcell** [comment]
@ansu5555 
Same issue:

Error screen shot attached.

![Screenshot_5](https://user-images.githubusercontent.com/43026377/80458349-44073980-894e-11ea-9d6e-6bdaa06239f5.png)

**Comment by ansu5555** [comment]
Provide the below additional details as the screenshot does not have enough details to point out the issue.

1. Attach or provide link to PDF
2. Steps to reproduce the problem

**Comment by vivek-gothi-openxcell** [comment]
@ansu5555 

Is pdf-viewer-reactjs support ssr? I am using this in my ssr base react js project.

**Comment by ansu5555** [comment]
Yes it does support ssr.
