### ISSUE TITLE
 if I don't initialize the document the first time it gives the error 'error while reading pages'

### ISSUE THREAD

**Issue by ialvira** [ansu5555/pdf-viewer-reactjs#22]
i have a problem when  charging PDF from base64 when i entry in to the applicattion the base64 Content is null an then when the user click botton the  pdf is charged and loaded the content in the<PDFViewer/> but the first time gives the error 'erro while reading pages'

my code is:

      <PDFViewer
          canvasCss={"miClase"}    
          hideNavbar={true}
          document={{
            base64: fichero,
          }}
        /
and my temporally solution is:

        <PDFViewer
          canvasCss={"miClase"}    
          hideNavbar={true}
          document={{
            base64: fichero===""?Sources.base64:fichero,
          }}
        />    

Do you have any idea why this is happening?

thank you
![image](https://user-images.githubusercontent.com/41111861/79464801-d4fb1e00-7ffa-11ea-80db-252ee2fcb204.png)

**Comment by ansu5555** [comment]
What I understood is that initially `fichero` variable is null and after you click some button it's getting populated.

So the error is expected as `document.base64` takes a string not a null. Just refrain loading the `pdf-viewer-reactjs` if the `fichero` is null.
