### ISSUE TITLE
JavaScript out of memory error.

### ISSUE THREAD

**Issue by oluwadareseyi** [ansu5555/pdf-viewer-reactjs#23]
Hello,

I installed the reader in one of my projects, but every time I start my React app, I get a ```JavaScript out of memory``` error.

![image](https://user-images.githubusercontent.com/48622375/79688295-5940e180-8245-11ea-8da6-d87864c5981c.png)

How can this be resolved? Once I remove it from my project, it starts working again, but I need the reader.

**Comment by ansu5555** [comment]
Setting `GENERATE_SOURCEMAP=false` in `.env` file solves this issue.
You can put it in your scripts in package.json as well.

```
  "scripts": {
    "start": "GENERATE_SOURCEMAP=false react-scripts start",
    "build": "GENERATE_SOURCEMAP=false react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  }
```

This issue is already raised check this [link](https://github.com/facebook/create-react-app/issues/8096) for details.

**Comment by oluwadareseyi** [comment]
I already sorted that out, thanks. Another thing, the package is distorting my already declared CSS rules. Is there a fix?.
