### ISSUE TITLE
Error with LaTeX generated file

### ISSUE THREAD

**Issue by SirHamburger** [ansu5555/pdf-viewer-reactjs#24]
Hello

At the moment i'm trying to render Latex files in your viewer.
Even with a single hello world compiled with `pdflatex main.tex` it doesn't work

The errors ar many invalid characters from pdf.worker.js and late an `InvalidPDFException {message: "Invalid PDF structure", name: "InvalidPDFException"}` 

One of the files which doesn't work is this one:
[main.pdf](https://github.com/ansu5555/pdf-viewer-reactjs/files/4510542/main.pdf)
Thers no issue with opening it in SumatraPDF, Adobe Reader or Edge.

I just include your PDFViewer with the document:
```import React, { Component } from "react";
import PDFViewer from "pdf-viewer-reactjs";
export default class Test extends Component {
  render() {
    return (
      <PDFViewer
        document={{
          url: "/main.pdf",
        }}
      />
    );
  }
}
```

Do you have any idea how to fix that issue?

Kind regards 
Simon

**Comment by ansu5555** [comment]
It's due to the import of the pdf file, import it like below and should work

```
import PDFViewer from "pdf-viewer-reactjs";
import PDF from './main.pdf'

export default class Test extends Component {
  render() {
    return (
      <PDFViewer
        document={{
          url: PDF,
        }}
      />
    );
  }
}
```

**Comment by SirHamburger** [comment]
Thank you very much. I thought i tried it but that was the problem.

Have a nice day and thanks for your nice viewer.

Kind regards

Simon
