### ISSUE TITLE
Shows the buttons without styling

### ISSUE THREAD

**Issue by LeandroSeoane** [ansu5555/pdf-viewer-reactjs#25]
Hi,

I applied the library in my project, wich is an app made with Electron and ReactJS and everything works fine, but, I don't know if I have to configure another property, but, I tried to implement the navbar on top and it's working but the buttons, like zoom in, zoom out, rotation, etc it's shows without styling:

![image](https://user-images.githubusercontent.com/29229455/80322855-0c897780-87fe-11ea-952e-36a1f93410cd.png)

I saw the example and my implementation is equal, I don't know why the buttons shows like the image that I attached.

I don't know if is an issue or I have to add other property, you can find my implementation in the following image:

![image](https://user-images.githubusercontent.com/29229455/80322946-8faacd80-87fe-11ea-89af-988e60dcd682.png)

I will be waiting for your response.

Thanks in advance.
Best regards

**Comment by ansu5555** [comment]
No that's it, you don't have to configure anything else.

It uses Bulma & Material icons for styling so somehow your css is overriding it's default style or its not getting installed.

**Comment by LeandroSeoane** [comment]
Ohhh I see the ligth. Thanks @ansu5555. My app use bootstrap so, now, I know why the buttons styling are broken. Thanks for the information and I recommend to you add this dependency in the documentation, because, maybe, you will have to response the same to other users in several times.
 
Thank you very very much.
 
Best Regards,
Leandro

**Comment by ansu5555** [comment]
Thanks for the suggestion, closing this issue as your query is resolved.

Feel free to open an issue if anything is there.
