### ISSUE TITLE
npm install pdf-viewer-reactjs neither yarn add pdf-viewer-reactjs working

### ISSUE THREAD

**Issue by sanchitwakekar** [ansu5555/pdf-viewer-reactjs#3]

**Comment by sanchitwakekar** [comment]
I am using Windows 10 and VS code

**Comment by iDuckDark** [comment]
Running `npm install --save string_decoder` or `yarn add string_decoder` worked for me

**Comment by ansu5555** [comment]
Working on updates and fixes, I will release a new version soon

**Comment by yasskate** [comment]
I think would be worth if you create some issues and improvements on the `Issues` tab and we could help, what do you think? :)

**Comment by ansu5555** [comment]
> I think would be worth if you create some issues or improvements on the `Issues` tab and we could help, what do you think? :)

Yes that will help, will do that.

**Comment by ansu5555** [comment]
@sanchitwakekar Could you please check if its fixed in the latest update

**Comment by ansu5555** [comment]
closing the issue as npm/yarn install is working in windows 10
