### ISSUE TITLE
pdf-viewer just allow one rotation -90, 0 or 90

### ISSUE THREAD

**Issue by LeandroSeoane** [ansu5555/pdf-viewer-reactjs#30]
Hi,

I just wanted to know why the library just allow one rotation to 90 or -90 degrees. That approach just works for some documents, but if you have a document upside down, how I gonna rotate 180 degrees?

is there any way to fix this?

I'll be waiting for your response.

Thanks in advance.

Leandro,

**Comment by ansu5555** [comment]
Sorry for the late reply, you have to modify the code and pass it to pdfjs.
