### ISSUE TITLE
Colours dont stay true

### ISSUE THREAD

**Issue by jamiegalbreath** [ansu5555/pdf-viewer-reactjs#31]
This doesnt stay true to colour. Images can become washed out.
It seems to strip off ICC colour profiles from the pdf and/or from images within the pdf

Tested on lots of pdfs.

Is there anyway to keep these?

**Comment by ansu5555** [comment]
Updated the pdfjs in latest build so do have a check and if the issue still persist then raise a bug in [pdfjs github](https://github.com/mozilla/pdf.js), as pdf processing is done by pdfjs.

**Comment by jamiegalbreath** [comment]
I appreciate you trying this, unfortunately, it still has the same issue. I will raise a bug like you say.
