### ISSUE TITLE
Distorts CSS when using semantic ui react.

### ISSUE THREAD

**Issue by CryceTruly** [ansu5555/pdf-viewer-reactjs#32]
After installing and importing the PDFViewer component in the application, most of the semantic ui react css is lost, works fine when the import is removed.

**Comment by 2000yeshu** [comment]
Same thing happens with me.

**Comment by ansu5555** [comment]
Removed bulma in latest release(v2.0.7), so it will not distort your exsisting css and you have to provide your own custom css for pdf-viewer.
