### ISSUE TITLE
How does the error handling works?

### ISSUE THREAD

**Issue by yasskate** [ansu5555/pdf-viewer-reactjs#4]
Hey @ansu5555 🤓 ✌️ 

I noticed there is no error handling on the dependency
I've tried to use the `PDFViewer` component but I'm passing a `URL` (like /my/file/pdf) on the 'url' property, this url provides a pdf document itself on the request but if the request response an error, my app crashes due to the `PDFViewer` lacks of `onError`handler method.

Do you have any idea how could I handle the error?

**Comment by ansu5555** [comment]
Yes same issue I have also faced and this can be handled from pdfjs,  currently working on it and include in next release.

**Comment by yasskate** [comment]
Thanks a lot!
if you need hands in order to release this faster just let me know, I could help :)

**Comment by ansu5555** [comment]
Thanks for the mention... I have released the new version with the error handling, please have a look.

**Comment by yasskate** [comment]
Awesome! 😃 
Thanks @ansu5555, it works properly.

When I have a chance I'll send a PR with an improvement for the error handling method, I'd like to create a new prop like 'onPdfError' which gets a custom component I think this would be worth, what do you think?

Thanks a lot! :D

**Comment by ansu5555** [comment]
As 

> Awesome! 
> Thanks @ansu5555, it works properly.
> 
> When I have a chance I'll send a PR with an improvement for the error handling method, I'd like to create a new prop like 'onPdfError' which gets a custom component I think this would be worth, what do you think?
> 
> Thanks a lot! :D

Sure, that will pretty useful, and as the error handling is added I am closing this issue.
