### ISSUE TITLE
Download PDF each time when click on Next

### ISSUE THREAD

**Issue by rezacse** [ansu5555/pdf-viewer-reactjs#40]
Here is my component 
```
import React from 'react';
import PDFViewer from 'pdf-viewer-reactjs';

const AppPDFViewer = ({ url }) => {
  return (
    <PDFViewer
      document={{
        url: 'https://arxiv.org/pdf/quant-ph/0410100.pdf'
      }}
      navbarOnTop
      
    />
  );
};

export default AppPDFViewer;
```

When it initially renders the pdf file is downloading multiple times. 
Also, when clicking on the next button, pdf downloaded every time.

![image](https://user-images.githubusercontent.com/7262341/90508221-1eaa6f80-e179-11ea-952a-056427d7e6e5.png)

**NB**: I am rendering mutliple pdf files at one page.

**Comment by ansu5555** [comment]
Fixed in version 2.1.1
