### ISSUE TITLE
How install peer dependency

### ISSUE THREAD

**Issue by mandala21** [ansu5555/pdf-viewer-reactjs#43]
This note 
```
Due to causing broken css issue bulma, bulma-helpers & material-design-icons are removed from dependencies and added as peerDependencies
Please install bulma, bulma-helpers & material-design-icons from npm by yourself or provide custom css as per your requirement
```
The readme contains this note but does not teach how to deal with it

Should I just give npm install on these packages?

because when I install the package in my project I receive the following warnings
```
./node_modules/pdf-viewer-reactjs/dist/pdf-viewer-reactjs.js
Module not found: Can't resolve 'bulma-helpers/css/bulma-helpers.min.css' in '/home/lucas/source/front-gabaricev/node_modules/pdf-viewer-reactjs/dist'

./node_modules/pdf-viewer-reactjs/dist/pdf-viewer-reactjs.js
Module not found: Can't resolve 'bulma/css/bulma.css' in '/home/lucas/source/front-gabaricev/node_modules/pdf-viewer-reactjs/dist'

./node_modules/pdf-viewer-reactjs/dist/pdf-viewer-reactjs.js
Module not found: Can't resolve 'material-design-icons/iconfont/material-icons.css' in '/home/lucas/source/front-gabaricev/node_modules/pdf-viewer-reactjs/dist'

```

I think that if i run npm install dont resolve this warning. Because the folders of modules in node_modules/pdf-viewer-reactjs

**Comment by ansu5555** [comment]
Peer Dependencies needs to be installed separately. You can search in google and learn about that.

**Comment by Amritpd** [comment]
HI there, you should provide step-by-step details instead of trusting people to figure it out. It is your job as the package maintainer to keep crystal clear instructions :)

**Comment by ansu5555** [comment]
> HI there, you should provide step-by-step details instead of trusting people to figure it out. It is your job as the package maintainer to keep crystal clear instructions :)

Well, I believe developers are pretty smart creatures...
