### ISSUE TITLE
CSS Caching

### ISSUE THREAD

**Issue by isakovicq** [ansu5555/pdf-viewer-reactjs#44]
Hi there, so with installed bulma, bulma-heleprs and icons, after visiting page where I am using your library to display PDF, styling in entire application is messed up, so is there a way to prevent that by either not using that at all and providing my own style to PDFViewer component or some other solution you are suggesting?

**Comment by ansu5555** [comment]
you can remove bulma and provide your own css classes. You can check this example [code](https://github.com/ansu5555/pdf-viewer-reactjs/blob/master/example/src/App.js#L128) & [css classes](https://github.com/ansu5555/pdf-viewer-reactjs/blob/master/example/src/App.css)
