### ISSUE TITLE
[BUG] Navigation Buttons without style

### ISSUE THREAD

**Issue by pmsferreira** [ansu5555/pdf-viewer-reactjs#49]
**Describe the bug**
I install this library (also installed bulma, bulma-helpers and material-icons libs). 
But the navigations buttons appears without styling.
I try to define a custom css for each button but I don't know why (a example could be helpfull)

**Screenshots**

Code:
![Screenshot 2020-11-10 at 09 27 50](https://user-images.githubusercontent.com/16557512/98655125-09d41700-2337-11eb-9ca6-04746a01b09f.png)

Result:
![Screenshot 2020-11-10 at 09 22 41](https://user-images.githubusercontent.com/16557512/98654812-b19d1500-2336-11eb-8561-2518c2a96a55.png)

in console I got:
 "Failed to decode downloaded font: <URL>"

**Additional context**
React App

**Comment by micahyeah** [comment]
Experiencing the same issue. Except I do not get the black bar either. I just get plain gray buttons with no styling whatsoever and the same button text as above.

**Comment by pmsferreira** [comment]
> Experiencing the same issue. Except I do not get the black bar either. I just get plain gray buttons with no styling whatsoever and the same button text as above.

And did you solve the problem ?

**Comment by micahyeah** [comment]
> > Experiencing the same issue. Except I do not get the black bar either. I just get plain gray buttons with no styling whatsoever and the same button text as above.
> 
> And did you solve the problem ?

Nope. Nothing I was doing was getting around it. I could add some custom styling to make it look basically the same, but the text of the buttons was still unchangeable and said things like (zoom_in, zoom_out, etc..)

**Comment by ansu5555** [comment]
There is some problem specific to your project/env so material icon is not getting decoded. You can try removing the node modules directory but not sure if it will work. Try to give your own navigation component if does not work. Checkout the below examples

https://github.com/ansu5555/pdf-viewer-reactjs/blob/c25c07991424915f6415c5ac20f8b249ec262e79/example/src/App.js#L129
https://github.com/ansu5555/pdf-viewer-reactjs/blob/c25c07991424915f6415c5ac20f8b249ec262e79/example/src/App.js#L158
