### ISSUE TITLE
Render all pages instead of a single page

### ISSUE THREAD

**Issue by hamzaahmed074** [ansu5555/pdf-viewer-reactjs#5]
Hi,
I was able to render and restyle the viewer but for a single page. My issue is how can i render all the pages for now only One page is render and the next page only comes after the navigation buttons are pressed. Is there any prop like showAllPages which will render all pages and we can change the pages while scrolling up and down. If there is none can you guide me in right direction.
Thanks

**Comment by ansu5555** [comment]
You have to render all the pages once the pdf is loaded and its not a good idea as it will be slow for large pdf files. However you can load a set of pages (e.g 5) at once and display. As of now such functionality is not available but can be added in future.

**Comment by ignatovladislav** [comment]
Hello, @ansu5555. I have issue. I need render all pages from pdf-file and i used this library. Its functionality added now?

**Comment by ansu5555** [comment]
> Hello, @ansu5555. I have issue. I need render all pages from pdf-file and i used this library. Its functionality added now?

No, It's still in progress and will be added soon

**Comment by sauslash** [comment]
Hi everyone, the pages functionality is available?

**Comment by MishchanchukA** [comment]
> > Hello, @ansu5555. I have issue. I need render all pages from pdf-file and i used this library. Its functionality added now?
> 
> No, It's still in progress and will be added soon

Hi. Do you have any news about rendering all pages?

**Comment by ansu5555** [comment]
No it's still in development.

**Comment by ansu5555** [comment]
Added in version 2.1.1, its has a thumbnail view for all the pages
