### ISSUE TITLE
Pdf view not displaying for base64 data

### ISSUE THREAD

**Issue by silpa4** [ansu5555/pdf-viewer-reactjs#50]
I installed this library to view uploaded pdf. I m converting the uploaded file as base 64.

**I m converting pdf to Base 64 as follows:**
var selectedFile = document.getElementById("inputFile").files;
        //Check File is not Empty
        if (selectedFile.length > 0) {
            // Select the very first file from list
            var fileToLoad = selectedFile[0];
            // FileReader function for read the file.
            var fileReader = new FileReader();
            var base64;
            // Onload of file read the file content
            fileReader.onload = function(fileLoadedEvent) {
                base64 = fileLoadedEvent.target.result;
                // Print data in console
                console.log(base64);
            };
            // Convert data to base64
            fileReader.readAsDataURL(fileToLoad);
        }

i m giving the base64 value to view the pdf. **But i m getting the following error in console**
**Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded**
![image](https://user-images.githubusercontent.com/25945923/98665374-9b607a80-2371-11eb-88a0-8c0db77d34b2.png)

**Comment by ansu5555** [comment]
you have to remove `data:application/pdf;base64,` from the generated base64 string to make it work.
