### ISSUE TITLE
Feature set width 100%

### ISSUE THREAD

**Issue by atsoares** [ansu5555/pdf-viewer-reactjs#53]
How to adjust the pdf to fit 100% width? It works perfectly on browser but on mobile doesnt

**Comment by ansu5555** [comment]
You can do it with 'scale' & 'canvasCss' props. Checkout [this repository](https://github.com/ansu5555/example-pdfviewer) for reference

![image](https://user-images.githubusercontent.com/5373653/100857409-ac089a00-34b2-11eb-8829-c080474bdbd5.png)

**Comment by ansu5555** [comment]
closing this issue as its solved.
