### ISSUE TITLE
Getting error while using npm run build in github actions auto deploy that "Module not found: Can't resolve 'bulma-helpers/css/bulma-helpers.min.css"

### ISSUE THREAD

**Issue by DhruvikBarvaliya** [ansu5555/pdf-viewer-reactjs#54]
[**Describe the bug**]
![Screenshot 2020-12-15 155607](https://user-images.githubusercontent.com/38715240/102203042-188d8b00-3eee-11eb-8455-e259ebd4c55b.png)

./node_modules/pdf-viewer-reactjs/dist/pdf-viewer-reactjs.js
Module not found: Can't resolve 'bulma-helpers/css/bulma-helpers.min.css' in '/home/dhruvik/actions-runner/node_modules/pdf-viewer-reactjs/dist'

./node_modules/pdf-viewer-reactjs/dist/pdf-viewer-reactjs.js
Module not found: Can't resolve 'bulma/css/bulma.css' in '/home/dhruvik/actions-runner/node_modules/pdf-viewer-reactjs/dist'

./node_modules/pdf-viewer-reactjs/dist/pdf-viewer-reactjs.js
Module not found: Can't resolve 'material-design-icons/iconfont/material-icons.css' in '/home/dhruvik/actions-runner/node_modules/pdf-viewer-reactjs/dist'

**Comment by ansu5555** [comment]
These are peer dependencies, should be installed separately.

Closing the bug as steps to reproduce the bug are missing.
