### ISSUE TITLE
Error while reading the pages ![BUG]

### ISSUE THREAD

**Issue by soheilhassanjani** [ansu5555/pdf-viewer-reactjs#55]
hi . i install this package when use it in my project , it display " Error while reading the pages ! " . please help mi to fix it

**Comment by ansu5555** [comment]
Closing as there is no detail provided, please reopen the bug with "bug report" template and provide all the details.

**Comment by soheilhassanjani** [comment]
Error while reading the pages !
 TypeError: Cannot set property 'height' of null
    at pdf-viewer-reactjs.js:1
    at tryCatch (runtime.js:45)
    at Generator.invoke [as _invoke] (runtime.js:274)
    at Generator.prototype.<computed> [as next] (runtime.js:97)
    at asyncGeneratorStep (asyncToGenerator.js:3)
    at _next (asyncToGenerator.js:25)

**Comment by ansu5555** [comment]
provide the pdf file and the code too

**Comment by soheilhassanjani** [comment]
at the first time , i clone this project and use example folder that is working good. but use the same base64 and code in my project could,t display it .

**Comment by ansu5555** [comment]
Then the problem is with your code I believe. If you want my help then please share your repository.
