### ISSUE TITLE
[BUG] Set page dynamically

### ISSUE THREAD

**Issue by emorling** [ansu5555/pdf-viewer-reactjs#56]
**Describe the bug**
Errors are thrown if you change the page prop after init.

**How to Reproduce**
1. Dynamically set the page prop of PDFViewer

`<PDFViewer
      document={{
        url: "",
      }}
      page={pageNumber}
    />`

**Expected behavior**
Ability to programatically change the page of an initialized viewer.

**Comment by emorling** [comment]
I am uncertain if this is a bug, or feature request :) I was expecting to be able to set the page

**Comment by ansu5555** [comment]
It's already there, checkout  this [example code](https://github.com/ansu5555/pdf-viewer-reactjs/blob/master/example/src/App.js#L98-#L110)

here is the live example https://ansu5555.github.io/pdf-viewer-reactjs/#csp

**Comment by emorling** [comment]
@ansu5555 I checked the code you linked to, but it is not dynamically updated the page number?

**Comment by ansu5555** [comment]
@emorling got it now, as a viewer all the control was from the navbar and nothing was created to set zoom, rotation or page dynamically after load from outside of navbar.

This is an enhancement and will incorporate in the next release

**Comment by emorling** [comment]
Ok! Any ETA on this?

**Comment by ansu5555** [comment]
> Ok! Any ETA on this?

will update you by Monday

**Comment by ansu5555** [comment]
Implemented in v2.2.1

Code:
https://github.com/ansu5555/pdf-viewer-reactjs/blob/master/example/src/App.js#L312-L500
Live Example:
https://ansu5555.github.io/pdf-viewer-reactjs/#ec

**Comment by emorling** [comment]
Very neat thanks! Well done!
