### ISSUE TITLE
[BUG] URL's given is different from what's rendered in PDF Viewer

### ISSUE THREAD

**Issue by MarioSerano** [ansu5555/pdf-viewer-reactjs#60]
**The bug**
In my project I wanted to render multiple PDF's in a single page. And I tried doing so but fails for some reason. It renders the first page, but then when I clicked next, it renders a different page of another pdf URL(which is in the page).

**How to Reproduce**
1. Create an app where it attempts to render multiple PDF's
2. After all things rendered and stable, click next on the one of the PDF's
3. If the PDF's you're looking at corresponds with the URL, try checking the other one

**Expected behavior**
Both PDF's render the actual PDF that corresponds with the URL given.

**Screenshots**
![image](https://user-images.githubusercontent.com/55081132/107872080-2190dd80-6eda-11eb-8660-bfcf99cd9142.png)
First PDF, First Render

![image](https://user-images.githubusercontent.com/55081132/107872093-33728080-6eda-11eb-8878-1600c918b47e.png)
Second PDF, First Render

First PDF after clicking next
![image](https://user-images.githubusercontent.com/55081132/107872109-4d13c800-6eda-11eb-8a24-84ad5866f6b0.png)

Second PDF after clicking next
![image](https://user-images.githubusercontent.com/55081132/107872115-5bfa7a80-6eda-11eb-8bb9-d5946dd7d051.png)

PDF's corresponding with the report:
FIRST PDF:
[TOR Anbita Nadine Siregar -  Startup Weekend Indonesia - Next Gen.pdf](https://github.com/ansu5555/pdf-viewer-reactjs/files/5977215/TOR.Anbita.Nadine.Siregar.-.Startup.Weekend.Indonesia.-.Next.Gen.pdf)
SECOND PDF:
[Lect 7-8 - MIPS ISA 2.pdf](https://github.com/ansu5555/pdf-viewer-reactjs/files/5977222/Lect.7-8.-.MIPS.ISA.2.pdf)

**Probably a bit helpful to know?**
![image](https://user-images.githubusercontent.com/55081132/107872185-f1960a00-6eda-11eb-9332-e123c2e5094e.png)
I hooked up my API to send the URL's, and I see that this is the waterfall of the network. Possibly related to this, so thought it might be helpful.

If it's not a bug, any fix that I can do? 
Or if it's a bug, please let me know so I can move to other solution. Thank you! :)

**Comment by ansu5555** [comment]
Its a bug... will look into it and update soon.

**Comment by ansu5555** [comment]
fixed in version 2.2.3

**Comment by MarioSerano** [comment]
> fixed in version 2.2.3

amazing, thanks for the quick fix! :D
