### ISSUE TITLE
[BUG] Password props type boolean

### ISSUE THREAD

**Issue by gius80** [ansu5555/pdf-viewer-reactjs#65]
I'm figuring out out to display password protected pdf.

Doc indicate **password** props, type string, but in the codebase the password props is boolean.

Thanks,
Igot

**Comment by gius80** [comment]
Sorry, it's a bug of the @types/pdf-viewer-reactjs package

**Comment by ansu5555** [comment]
Thanks for pointing out its fixed in version 2.2.1

https://www.npmjs.com/package/@types/pdf-viewer-reactjs/v/2.2.1
