### ISSUE TITLE
[BUG] PDF does not align to the center

### ISSUE THREAD

**Issue by tofiqquadri** [ansu5555/pdf-viewer-reactjs#68]
**Describe the bug**
PDF content doesn't align to the centre.

**How to Reproduce**
Steps to reproduce the behaviour:
1. Load the PDF using:

```
<PDFViewer document={{
            url: 'https://arxiv.org/pdf/quant-ph/0410100.pdf',
}} />
```

2. The PDF loads with left alignment

**Expected behaviour**
The PDF should align with the centre by default. If not there should be an option to align the pdf content.

**Screenshots**
![image](https://user-images.githubusercontent.com/16437112/110285214-e9784880-8008-11eb-874b-bcc79b004e71.png)

**PDF File**
https://arxiv.org/pdf/quant-ph/0410100.pdf

**Details (please complete the following information):**
 - Device: [Desktop]
 - OS: [Windows 10]
 - Browser [safari, chrome]
 - Version [2.2.3]

**Comment by ansu5555** [comment]
It does...
![image](https://user-images.githubusercontent.com/5373653/110310159-36b7e280-8028-11eb-9300-b177245a5b94.png)

Use **css** & **canvasCss** props to customize...
