### ISSUE TITLE
Error Compiling

### ISSUE THREAD

**Issue by josedager** [ansu5555/pdf-viewer-reactjs#7]
Each time i add your Component to my react-app i got a compiling error...

<--- Last few GCs --->

[13048:000001BD16F70C40]   108875 ms: Scavenge 2035.9 (2050.6) -> 2035.2 (2050.8) MB, 7.1 / 0.0 ms  (average mu = 0.063, current mu = 0.000) allocation failure
[13048:000001BD16F70C40]   111455 ms: Mark-sweep 2036.5 (2051.1) -> 2034.4 (2051.1) MB, 2579.0 / 0.1 ms  (average mu = 0.048, current mu = 0.025) allocation failure scavenge might not succeed

<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 00007FF723BB2A5D]
Security context: 0x0171417408a1 <JSObject>
    1: SourceMapConsumer_allGeneratedPositionsFor [000001F3D23145B1] [C:\Users\JoseDM\sim-frontend\node_modules\@babel\core\node_modules\source-map\lib\source-map-consumer.js:~178] [pc=000002CBB974D24D](this=0x00f7f1b80219 <BasicSourceMapConsumer map = 000003C69CB828C1>,0x01d3abd3e979 <Object map = 0000024F40A3DAB1>)
    2: /* anonymous */(aka /* anonymous...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

Writing Node.js report to file: report.20191217.140536.13048.0.001.json
Node.js report completed
 1: 00007FF722FE076F napi_wrap+124431
 2: 00007FF722F824B6 public: bool __cdecl v8::base::CPU::has_sse(void)const __ptr64+34502
 3: 00007FF722F83176 public: bool __cdecl v8::base::CPU::has_sse(void)const __ptr64+37766
 4: 00007FF723786D3E private: void __cdecl v8::Isolate::ReportExternalAllocationLimitReached(void) __ptr64+94
 5: 00007FF72376ED81 public: class v8::SharedArrayBuffer::Contents __cdecl v8::SharedArrayBuffer::Externalize(void) __ptr64+833
 6: 00007FF72363C64C public: static void __cdecl v8::internal::Heap::EphemeronKeyWriteBarrierFromCode(unsigned __int64,unsigned __int64,class v8::internal::Isolate * __ptr64)+1436
 7: 00007FF7236479F0 public: void __cdecl v8::internal::Heap::ProtectUnprotectedMemoryChunks(void) __ptr64+1312
 8: 00007FF723644524 public: static bool __cdecl v8::internal::Heap::PageFlagsAreConsistent(class v8::internal::HeapObject)+3204
 9: 00007FF723639DB3 public: bool __cdecl v8::internal::Heap::CollectGarbage(enum v8::internal::AllocationSpace,enum v8::internal::GarbageCollectionReason,enum v8::GCCallbackFlags) __ptr64+1283
10: 00007FF723638584 public: void __cdecl v8::internal::Heap::AddRetainedMap(class v8::internal::Handle<class v8::internal::Map>) __ptr64+2356
11: 00007FF723659855 public: class v8::internal::Handle<class v8::internal::HeapObject> __cdecl v8::internal::Factory::NewFillerObject(int,bool,enum v8::internal::AllocationType) __ptr64+53
12: 00007FF7233C6029 ??4iterator@JumpTableTargetOffsets@interpreter@internal@v8@@QEAAAEAV01234@$$QEAV01234@@Z+4057
13: 00007FF723BB2A5D public: virtual bool __cdecl v8::internal::SetupIsolateDelegate::SetupHeap(class v8::internal::Heap * __ptr64) __ptr64+567949
14: 000002CBB974D24D
npm ERR! code ELIFECYCLE
npm ERR! errno 134
npm ERR! sim@0.1.0 start: `react-scripts start`
npm ERR! Exit status 134
npm ERR!
npm ERR! Failed at the sim@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\JoseDM\AppData\Roaming\npm-cache\_logs\2019-12-17T19_05_37_011Z-debug.log

Can you help me?

**Comment by NuclleaR** [comment]
Have the same issue.
@josedager do you know how to solve?

**Comment by mrfambo** [comment]
Anyone Solved the issue?

**Comment by dutchviewgaurav** [comment]
Any Solution?  @josedager
