### ISSUE TITLE
Just cloned. but unable to run example app

### ISSUE THREAD

**Issue by abitgen** [ansu5555/pdf-viewer-reactjs#71]
I have cloned the repo and 

did cd to example, then did "yarn install" followed by "yarn start",

but it shows **'react-scripts' is not recognized as an internal or external command,**

Later I tried installing all peer dependencies mentioned in root project, still the same issue.

I know this should not be a expected behavior, but I am stuck.

Please provide any solution for the same and also kindly update the docs.

**Comment by ansu5555** [comment]
Clone the tagged version v2.2.3
https://github.com/ansu5555/pdf-viewer-reactjs/tree/v2.2.3
