### ISSUE TITLE
Error loading pdf from url

### ISSUE THREAD

**Issue by Ali-hd** [ansu5555/pdf-viewer-reactjs#9]
Hi 

I'm trying to preview the pdf from this link https://xamber.s3.amazonaws.com/Result.pdf but it's not working?

**Comment by ansu5555** [comment]
Your S3 bucket  does not have CORS permission, please configure CORS in your bucket. This [link](https://docs.aws.amazon.com/AmazonS3/latest/dev/cors.html) might be useful for that.


I got the below error when I tried to access the document

```
localhost/:1 Access to fetch at 'https://xamber.s3.amazonaws.com/Result.pdf' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

**Comment by irosadie** [comment]
try https://cors-anywhere.herokuapp.com/{yourpdflink}
